export type Company = {
  id: string;
  name: string;
  domain: string;
  logo: string;
  tagline: string;
  description: string;
  focus: string[];
  founded: number;
  founders: string[];
  location: string;
  employeeCount: number;
};

export const companies: Company[] = [
  {
    id: '1',
    name: 'ByteDance',
    domain: 'bytedance.com',
    logo: 'https://genai.owasp.org/wp-content/uploads/2025/02/blogo-67c0f93549138.png',
    tagline: 'Inspire Creativity, Enrich Life',
    description:
      'ByteDance is a global internet technology company, owning products like TikTok, Douyin, Toutiao, etc.',
    focus: ['Content', 'Social', 'AI'],
    founded: 2012,
    founders: ['Yiming Zhang'],
    location: 'Beijing',
    employeeCount: 100000,
  },
  {
    id: '2',
    name: 'Tencent',
    domain: 'tencent.com',
    logo: 'https://www.tencent.com/img/index/tencent_logo.png',
    tagline: 'Connecting Everything',
    description:
      'Tencent is a technology and cultural company based on the internet, with products including WeChat, QQ, etc.',
    focus: ['Social', 'Gaming', 'Cloud Computing'],
    founded: 1998,
    founders: ['Pony Ma'],
    location: 'Shenzhen',
    employeeCount: 80000,
  },
  {
    id: '3',
    name: 'Alibaba',
    domain: 'alibaba.com',
    logo: 'https://s3-eu-west-1.amazonaws.com/tpd/logos/46d37463000064000500b136/0x0.png',
    tagline: 'Make it easy to do business anywhere',
    description:
      'Alibaba Group is a global leading internet company, covering e-commerce, cloud computing, finance, etc.',
    focus: ['E-commerce', 'Cloud Computing', 'Finance'],
    founded: 1999,
    founders: ['Jack Ma'],
    location: 'Hangzhou',
    employeeCount: 110000,
  },
  {
    id: '4',
    name: 'Google',
    domain: 'google.com',
    logo: 'https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_92x30dp.png',
    tagline: 'Organize the world’s information',
    description:
      'Google specializes in Internet-related services and products, including search, cloud computing, and advertising.',
    focus: ['Search', 'Cloud', 'AI'],
    founded: 1998,
    founders: ['Larry Page', 'Sergey Brin'],
    location: 'Mountain View',
    employeeCount: 156500,
  },
  {
    id: '5',
    name: 'Microsoft',
    domain: 'microsoft.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/4/44/Microsoft_logo.svg',
    tagline: 'Empower every person and every organization',
    description:
      'Microsoft develops, licenses, and supports software, services, devices, and solutions worldwide.',
    focus: ['Software', 'Cloud', 'AI'],
    founded: 1975,
    founders: ['Bill Gates', 'Paul Allen'],
    location: 'Redmond',
    employeeCount: 221000,
  },
  {
    id: '6',
    name: 'Apple',
    domain: 'apple.com',
    logo: 'https://logo.com/image-cdn/images/kts928pd/production/9fa92ac5a9498502d2707ced798d763fe7490ecc-1600x1026.png?w=1920&q=72&fm=webp',
    tagline: 'Think Different',
    description:
      'Apple designs, manufactures, and markets smartphones, personal computers, tablets, and wearables.',
    focus: ['Hardware', 'Software', 'Design'],
    founded: 1976,
    founders: ['Steve Jobs', 'Steve Wozniak', 'Ronald Wayne'],
    location: 'Cupertino',
    employeeCount: 164000,
  },
  {
    id: '7',
    name: 'Amazon',
    domain: 'amazon.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Amazon_logo.svg',
    tagline: 'Work Hard. Have Fun. Make History.',
    description:
      'Amazon is a multinational technology company focusing on e-commerce, cloud computing, and AI.',
    focus: ['E-commerce', 'Cloud', 'AI'],
    founded: 1994,
    founders: ['Jeff Bezos'],
    location: 'Seattle',
    employeeCount: 1608000,
  },
  {
    id: '8',
    name: 'Meta',
    domain: 'meta.com',
    logo: 'https://static.vecteezy.com/system/resources/previews/055/210/890/non_2x/meta-logo-square-rounded-meta-logo-meta-logo-free-download-free-png.png',
    tagline: 'Give people the power to build community',
    description:
      'Meta Platforms is the parent company of Facebook, Instagram, WhatsApp, and Oculus.',
    focus: ['Social', 'VR', 'AI'],
    founded: 2004,
    founders: ['Mark Zuckerberg'],
    location: 'Menlo Park',
    employeeCount: 86000,
  },
  {
    id: '9',
    name: 'Netflix',
    domain: 'netflix.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg',
    tagline: 'See What’s Next',
    description:
      'Netflix is a streaming service that offers a wide variety of award-winning TV shows, movies, anime, and documentaries.',
    focus: ['Streaming', 'Content', 'Tech'],
    founded: 1997,
    founders: ['Reed Hastings', 'Marc Randolph'],
    location: 'Los Gatos',
    employeeCount: 12900,
  },
  {
    id: '10',
    name: 'Tesla',
    domain: 'tesla.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/b/bd/Tesla_Motors.svg',
    tagline: 'Accelerate the world’s transition to sustainable energy',
    description:
      'Tesla designs, develops, manufactures, and sells electric vehicles and energy storage products.',
    focus: ['Automotive', 'Energy', 'AI'],
    founded: 2003,
    founders: ['Elon Musk'],
    location: 'Palo Alto',
    employeeCount: 127855,
  },
  {
    id: '11',
    name: 'IBM',
    domain: 'ibm.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/51/IBM_logo.svg',
    tagline: 'Let’s put smart to work',
    description:
      'IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services.',
    focus: ['Cloud', 'AI', 'Consulting'],
    founded: 1911,
    founders: ['Charles Ranlett Flint'],
    location: 'Armonk',
    employeeCount: 288300,
  },
  {
    id: '12',
    name: 'Intel',
    domain: 'intel.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/6/64/Intel-logo-2022.png',
    tagline: 'Engineering the future',
    description:
      'Intel is a global leader in the semiconductor industry, creating world-changing technology.',
    focus: ['Semiconductor', 'AI', 'Hardware'],
    founded: 1968,
    founders: ['Robert Noyce', 'Gordon Moore'],
    location: 'Santa Clara',
    employeeCount: 131900,
  },
  {
    id: '13',
    name: 'Samsung',
    domain: 'samsung.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/2/24/Samsung_Logo.svg',
    tagline: 'Inspire the World, Create the Future',
    description:
      'Samsung is a South Korean multinational conglomerate, a leader in electronics and digital media.',
    focus: ['Electronics', 'Display', 'Mobile'],
    founded: 1938,
    founders: ['Lee Byung-chul'],
    location: 'Seoul',
    employeeCount: 266673,
  },
  {
    id: '14',
    name: 'Oracle',
    domain: 'oracle.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/5/50/Oracle_logo.svg',
    tagline: 'Data drives everything',
    description:
      'Oracle is a global leader in database software, cloud solutions, and enterprise software products.',
    focus: ['Database', 'Cloud', 'Software'],
    founded: 1977,
    founders: ['Larry Ellison', 'Bob Miner', 'Ed Oates'],
    location: 'Austin',
    employeeCount: 143000,
  },
  {
    id: '15',
    name: 'Salesforce',
    domain: 'salesforce.com',
    logo: 'https://www.sparkplug.ai/wp-content/uploads/2023/10/salesforce-logo.png',
    tagline: 'We bring companies and customers together',
    description:
      'Salesforce is a cloud-based software company providing customer relationship management service.',
    focus: ['CRM', 'Cloud', 'AI'],
    founded: 1999,
    founders: ['Marc Benioff'],
    location: 'San Francisco',
    employeeCount: 73541,
  },
  {
    id: '16',
    name: 'Adobe',
    domain: 'adobe.com',
    logo: 'https://logos-world.net/wp-content/uploads/2020/06/Adobe-Logo-1993-2014.png',
    tagline: 'Changing the world through digital experiences',
    description:
      'Adobe is a global leader in digital media and digital marketing solutions.',
    focus: ['Software', 'Design', 'Cloud'],
    founded: 1982,
    founders: ['John Warnock', 'Charles Geschke'],
    location: 'San Jose',
    employeeCount: 29000,
  },
  {
    id: '17',
    name: 'Uber',
    domain: 'uber.com',
    logo: 'https://cdn.worldvectorlogo.com/logos/uber-11.svg',
    tagline: 'Move the way you want',
    description:
      'Uber develops and operates proprietary technology applications supporting a variety of offerings on its platform.',
    focus: ['Mobility', 'Logistics', 'AI'],
    founded: 2009,
    founders: ['Garrett Camp', 'Travis Kalanick'],
    location: 'San Francisco',
    employeeCount: 32500,
  },
  {
    id: '18',
    name: 'Spotify',
    domain: 'spotify.com',
    logo: 'https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg',
    tagline: 'Music for everyone',
    description:
      'Spotify is a digital music service that gives you access to millions of songs.',
    focus: ['Music', 'Streaming', 'Tech'],
    founded: 2006,
    founders: ['Daniel Ek', 'Martin Lorentzon'],
    location: 'Stockholm',
    employeeCount: 8800,
  },
  {
    id: '19',
    name: 'Zoom',
    domain: 'zoom.us',
    logo: 'https://static.vecteezy.com/system/resources/previews/012/871/376/non_2x/zoom-logo-in-blue-colors-meetings-app-logotype-illustration-free-png.png',
    tagline: 'Meet Happy',
    description:
      'Zoom is a communications technology company known for its video conferencing platform.',
    focus: ['Video', 'Cloud', 'Tech'],
    founded: 2011,
    founders: ['Eric Yuan'],
    location: 'San Jose',
    employeeCount: 8700,
  },
  {
    id: '20',
    name: 'Shopify',
    domain: 'shopify.com',
    logo: 'https://cdn3.iconfinder.com/data/icons/social-media-2068/64/_shopping-512.png',
    tagline: 'Make commerce better for everyone',
    description:
      'Shopify is a leading global commerce company, providing trusted tools to start, grow, market, and manage a retail business.',
    focus: ['E-commerce', 'Cloud', 'Tech'],
    founded: 2006,
    founders: ['Tobias Lütke', 'Daniel Weinand', 'Scott Lake'],
    location: 'Ottawa',
    employeeCount: 11000,
  },
];
